-- AlterTable
ALTER TABLE "FeePayment" ADD COLUMN IF NOT EXISTS "receiptImageUrl" VARCHAR(500) NOT NULL DEFAULT '';
ALTER TABLE "FeePayment" ADD COLUMN IF NOT EXISTS "description" VARCHAR(500) NOT NULL DEFAULT '';
